apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app/bia-deploy.yml
- app/bia-service.yml
- app/bia-hpa.yml
- ingress.yml
- argocd/

images:
- name: 976808777516.dkr.ecr.us-east-1.amazonaws.com/bia
  newName: 976808777516.dkr.ecr.us-east-1.amazonaws.com/bia
  newTag: 2973aa8290a80733bf5b99a7cc8eb82f8691c3a5
