apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app/bia-deploy.yml
- app/bia-service.yml
- ingress.yml
- argocd/

images:
- name: 976808777516.dkr.ecr.us-east-1.amazonaws.com/bia
  newName: 976808777516.dkr.ecr.us-east-1.amazonaws.com/bia
  newTag: a106fe7d38f8e708bb9fba1ebf3d798ceab1a4d1
